[package]
author = "coder-li"
name = "pngme"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0.30"
anyhow = "1.0.57"
crc = "3.0.0"
clap = { version = "3.2.8", features = ["derive"] }
